### PR TITLE
Support for GHC 9.6

### LINKED ISSUE #19: GHC 9.6 support
Tracking issue for GHC 9.6 support

### PR DESCRIPTION
**Pull request by Kleidukos**
Mostly CPP for imports.

closes #19

### CODE REVIEW

**Comment by jonascarpay** [comment]
Thanks! Would you mind cherrypicking/rebasing onto https://github.com/jonascarpay/calligraphy/tree/ghc96? It adds GHC 9.6 and should now properly trigger on PRs.

**Comment by tchoutri** [comment]
Sure! 
Btw, when you said that you preferred to merge to "staging" branches, I didn't immediately understand it. Would you consider having `development` for merging PRs and `main` whence they are released?

**Comment by Kleidukos** [comment]
Sure!
Btw, when you said that you preferred to merge to "staging" branches, I didn't immediately understand it. Would you consider having development for merging PRs and main whence they are released?

**Comment by jonascarpay** [comment]
Oh, no, I don't think we need a separate development branch. I'm happy to just have feature branches that merge into main, as long as every merge commit is green. For #17 I needed to bump and fix CI before merging, and since it didn't trigger on PRs yet that was the quickest way for me to do that.

**Review by jonascarpay — APPROVED** [review]
LGTM! Feel free to merge when green.

**Comment by jonascarpay** [comment]
Hmm, I'll take a look at the Nix failure

**Comment by jonascarpay** [comment]
I'm not allowed to push myself, but if you cherry-pick/rebase 2a7ef0aff926efb26a3a329fc7549e1b906cafc3 we should be good

**Pull request merged**
